### ISSUE TITLE
Failed to get UTC datetime from mongodb server, using local UTC

### ISSUE THREAD

**Issue by ouell** [gottscj/Hangfire.Mongo#390]
Hello everything is fine?

I have this issue and i have the following logs:
![image](https://github.com/gottscj/Hangfire.Mongo/assets/18268067/0571bba6-c77c-4007-a4b6-a4ad48a06975)

Stacktrace
```
at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.ProcessResponse(ConnectionId connectionId, CommandMessage responseMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, ICoreSession session, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1.ExecuteProtocol(IChannelHandle channel, ICoreSessionHandle session, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.RetryableReadOperationExecutor.Execute[TResult](IRetryableReadOperation`1 operation, RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.ReadCommandOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(RetryableReadContext context, CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.Aggregate[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at Hangfire.Mongo.MongoConnection.GetUtcDateTime()
```

Exception.message:
```
Command aggregate failed: Use of undefined variable: NOW.
```

Fields.State:
```
Failed to get UTC datetime from mongodb server, using local UTC
```

Configurations from my application:
```
    public static IServiceCollection AddHangfireConfiguration(this IServiceCollection services)
    {
        services.AddHangfire((prov, config) =>
        {
            config.UseActivator(new AspNetCoreJobActivator(prov.GetService<IServiceScopeFactory>()));
            config.UseStorage(prov.GetRequiredService<IJobStorageFactory>().GetJobStorage());
            config.UseFilter(new AutomaticRetryAttribute {Attempts = 0, LogEvents = false});
        });

        services.AddHangfireServer();

        services.AddSingleton<IJobStorageFactory, MongoDbJobStorageFactory>();

        services.AddHostedService<HangFireJobsRegisterer>();

        return services;
    }
```
```
public class MongoDbJobStorageFactory : IJobStorageFactory
{
    public JobStorage GetJobStorage()
    {
        var connectionString = EnvironmentVariableProvider.Instance.Get("CONNECTION_STRING_HANGFIRE");
        var mongoUrlBuilder = new MongoUrlBuilder(connectionString);

        var options = new MongoStorageOptions
        {
            MigrationOptions = new()
            {
                MigrationStrategy = new DropMongoMigrationStrategy(),
                BackupStrategy = new NoneMongoBackupStrategy()
            },
            Prefix = "Integradores-QrCode.Hangfire",
            CheckConnection = false,
            CheckQueuedJobsStrategy = CheckQueuedJobsStrategy.TailNotificationsCollection
        };

        return new MongoStorage(MongoClientSettings.FromConnectionString(connectionString),
                                mongoUrlBuilder.DatabaseName, options);
    }
}
```

**Comment by gottscj** [comment]
@ouell,

it seems you have a database older than v4.2 which doesnt support the aggregation $$NOW. Hangfire.Mongo will fallback to using the servers UTC time instead of Mongodb's. 
Its not critical.
the latest version falls back to using "serverStatus" instead of `Datetime.UtcNow`

You can also create a class which inherits MongoStorage and override the Features dictionary and set the 
`JobStorageFeatures.Connection.GetUtcDateTime` to false.

As it is a read only dictionary remember to add all the other flags which are supported.
you can see all the supported features here:

https://github.com/gottscj/Hangfire.Mongo/blob/4b35788378ecca589fde5ed814a589530823ad82/src/Hangfire.Mongo/MongoConnection.cs#L682

I hope this helps

**Comment by ouell** [comment]
It's solve my problem.

thx
